import 'bootstrap/dist/css/bootstrap.min.css';
import { Inter } from "next/font/google";
import Head from 'next/head'
import Script from 'next/script'
import "./globals.css";
import Nav from '@/components/Nav';
import Footer from '@/components/Footer';
import Header from '@/components/Header';
import { Poppins } from 'next/font/google';


const inter = Inter({ subsets: ["latin"] });

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '700'], // Add desired weights
  style: ['normal', 'italic'], // Add desired styles
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
      <link
        rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
        crossorigin="anonymous"
      />
      </Head>
      <Script src="https://kit.fontawesome.com/e04ed0b4fb.js" crossorigin="anonymous"></Script>

      <body className={`${inter.className} overflow-x-hidden`}>
        <Header className={poppins.className}/>
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
